### ISSUE TITLE
QUESTION ABOUT SYNCING DIFFERENT GMAILS ACCOUNT

### ISSUE THREAD

**Issue by nicosilber** [gaubert/gmvault#219]
Hello gaubert I have one question regarding syncing different account.
I know evey time I sync a gmail account all mails are saved locally in C:\Users\username\gmvault-db
What happens if I sync a new gmail account? This overwrites the previous backup? or it is made in a different folder?
Right now i finnished syncing one account and i want to sync another one...should i first save this folders before syncing the new account? 
Thank you
Nicolas

**Comment by gaubert** [comment]
@nicosilber I would appreciate if you could send me an email for your personal questions instead of creating issue in Github everytime. You can also post on the mailing list and you will get an answer. Next time I will close the issue without answering. Thanks for the understanding.

For supporting a second account you have to use another gmvault-db dir with -d. Do gmvault sync --help and you will have the detailed explanations.
