### ISSUE TITLE
let the user set the destination folder

### ISSUE THREAD

**Issue by afcuttin** [gaubert/gmvault#287]
I'd like to be able to set the destination folder of the backup

**Comment by gaubert** [comment]
You can do it.

$> gmvault sync myemail@gmail.com -d /tmp/custom-dir

See below the usage of the tool when you do:
$> gmvault sync --help
 usage: gmvault sync [-h] [-t TYPE] **[-d DB_DIR]** [-y] [-p] [--renew-oauth2-tok]
                    [--renew-passwd] [--store-passwd] [-r REQ] [-g REQ]
                    [--resume] [--emails-only] [--chats-only] [-e] [-c VAL]
                    [-m] [--no-compression] [--server HOSTNAME] [--port PORT]
                    [--debug]
                    email

positional arguments:
  email                 email to sync with.

optional arguments:
  -h, --help            show this help message and exit
  -t TYPE, -type TYPE, --type TYPE
                        type of synchronisation: full|quick|custom. (default:
                        full)
  **-d DB_DIR, --db-dir DB_DIR
                        Database root directory. (default: $HOME/gmvault-db)**
  -y, --oauth2          use oauth for authentication. (default recommended
                        method)
  -p, --passwd          use interactive password authentication. (not
                        recommended)
  --renew-oauth2-tok    renew the stored oauth token (two legged or normal)
                        via an interactive authentication session.
  --renew-passwd        renew the stored password via an interactive
                        authentication session. (not recommended)
  --store-passwd        use interactive password authentication, encrypt and
                        store the password. (not recommended)
  -r REQ, --imap-req REQ
                        Imap request to restrict sync.
  -g REQ, --gmail-req REQ
                        Gmail search request to restrict sync as defined inhtt
                        ps://support.google.com/mail/bin/answer.py?hl=en&answe
                        r=7190
  --resume, --restart   Resume the sync action from the last saved gmail id.
  --emails-only         Only sync emails.
  --chats-only          Only sync chats.
  -e, --encrypt         encrypt stored email messages in the database.
  -c VAL, --check-db VAL
                        enable/disable the removal from the gmvault db of the
                        emails that have been deleted from the given gmail
                        account. VAL = yes or no.
  -m, --multiple-db-owner
                        Allow the email database to be synchronized with
                        emails from multiple accounts.
  --no-compression      disable email storage compression (gzip).
  --server HOSTNAME     Gmail imap server hostname. (default: imap.gmail.com)
  --port PORT           Gmail imap server port. (default: 993)
  --debug, -debug       Activate debugging info

Examples:

a) Full synchronisation with email and oauth login in ./gmvault-db

#> gmvault sync foo.bar@gmail.com

b) Quick daily synchronisation (only the last 2 months are scanned)

#> gmvault sync --type quick foo.bar@gmail.com

c) Resume Full synchronisation from where it failed to not go through your mailbox again

#> gmvault sync foo.bar@gmail.com --resume

d) Encrypt stored emails to save them safely anywhere

#> gmvault sync foo.bar@gmail.com --encrypt

d) Custom synchronisation with an IMAP request for advance users

#> gmvault sync --type custom --imap-req "Since 1-Nov-2011 Before 10-Nov-2011" foo.bar@gmail.com

e) Custom synchronisation with an Gmail request for advance users.
   Get all emails with label work and sent by foo.

#> gmvault sync --type custom --gmail-req "in:work from:foo" foo.bar@gmail.com `


I will close it

**Comment by afcuttin** [comment]
ok, thanks
I didn't see the `-d` option in the cli help

**Comment by gaubert** [comment]
No problems. Your welcome.

**Comment by afcuttin** [comment]
very fast support, indeed!
Now backing up my two accounts, and automated the task in crontab ;)

**Comment by gaubert** [comment]
Super !!!
